<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>AegisVault.Platform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AegisVault.Core\AegisVault.Core.csproj" />
  </ItemGroup>

</Project>
